lib/ngx/ssl.md

Looks like the syntax section wasn't modified after copy-pasting.

Fix 'ssl.server_name' documentation

---

lib/ngx/ssl.md

I noticed this new function, but had a hard time finding it in the doc because it was missing from the table of contents.

Adding missing link in table of contents for ngx.ssl

---

lib/ngx/ssl.lua

Both `cert_pem_to_der` and `priv_key_pem_to_der` check to ensure that `__ngx_req` exists. At no point in either function is the request used (it would appear to be a holdover from other functions). This is problematic because both functions ['can be called in whatever contexts'](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ssl.md#cert_pem_to_der) but init_by_lua does not have a request.
This pull request removes the check for `__ngx_req` from both `cert_pem_to_der` and `priv_key_pem_to_der`, and allows both fucntions to be used in init_by_lua.

Remove request check from {priv_key,cert}_pem_to_der in ssl.lua

---

.travis.yml
README.markdown
lib/ngx/ssl/session.lua
lib/ngx/ssl/session.md
t/ssl-session-fetch.t
t/ssl-session-store.t

This Lua module provides Lua APIs for the contexts ssl_session_fetch_by_lua* and ssl_session_store_by_lua*.
See https://github.com/openresty/lua-nginx-module/pull/822 for more details.

feature: added the ngx.ssl.session module

---

t/ngx-resp.t

tests: $init_by_lua_block should be used inside the template in ngx-resp.t.

---

lib/ngx/process.md

doc: ngx.process: 'priviledged' should be privileged.

---

lib/resty/core.lua
lib/resty/core/misc.lua
t/os-getenv-hup.t
t/os-getenv.t
t/stream/os-getenv-hup.t
t/stream/os-getenv.t

Sister PR: https://github.com/openresty/lua-nginx-module/pull/1343

feature: make os.getenv see env directives in init_by_lua.

---

.gitignore

Ignore test servroots such as t/servroot_11588/ generated when running
the test suite with TEST_NGINX_RANDOMIZE=1.

misc: gitignore: add parallel tests servroots.

---

t/shdict.t
t/stream/shdict.t

tests: shdict.t: hardened 'init_ttl' test cases to ensure keys expire.

---

t/ndk.t
t/ocsp.t
t/ssl.t
t/stream/ssl.t

On our AWS EC2 test cluster, these tests fail if the lua-resty-core test
suite gets executed on an instance also executing the ngx_lua or
ngx_stream_lua test suites, since the latter two have iptables rules to
drop packet on this specific IP/port couple.
Instead of removing the rule from opsboy, changing the port here will
also ease local development process for maintainers. Only lua-resty-core
seems to be using this IP/port couple from the OpenResty components.

tests: avoided listening on 127.0.0.2:12345 on which iptables drops packets for ngx_lua and ngx_stream_lua tests suites.

---

lib/ngx/errlog.lua
lib/ngx/re.lua
lib/resty/core/exit.lua
lib/resty/core/misc.lua
lib/resty/core/phase.lua
lib/resty/core/regex.lua
lib/resty/core/request.lua
lib/resty/core/response.lua
lib/resty/core/shdict.lua
lib/resty/core/var.lua
t/shdict.t
t/stream/errlog-raw-log.t
t/var.t

It is almost never useful for a user to see a stacktrace pointing to
lua-resty-core. Additionally, many ngx_http_lua test cases fail since
they expect stacktraces to point to specific Lua handlers.
This prevents stacktraces such as:
runtime error: ../lua-resty-core/lib/resty/core/exit.lua:\d+: API disabled...
And instead ensures that stack traces look like:
runtime error: content_by_lua(nginx.conf:\d+):\d+: API disabled...

misc: updated calls to 'error()' to be thrown from the user's stack level.

---

lib/resty/core/misc.lua
t/os-getenv.t
t/stream/os-getenv.t

Thanks Luke Gorrie for the report!

bugfix: ensured 'os.getenv' can be localized before/after loading resty.core.

---

lib/resty/core/shdict.lua
t/shdict.t

bugfix: ensured resty.core can be loaded in NGINX < 1.11.7.

---

lib/resty/core/regex.lua
lib/resty/core/request.lua
lib/resty/core/utils.lua
t/re-bugs.t
t/utils.t

This is a follow up to d046562 which improves the heuristics to decide
whether PCRE JIT compilation should be disabled in init phase under
macOS or not. The heuristics now are:
- If under macOS
- If using PCRE 8.43 or greater
- Then PCRE JIT compilation will be disabled in the init phase
While PCRE JIT compilation is disabled as such, a notice log will notify
users attempting to use the `j` or `o` flags.
Once past the init phase, we revert the workaround and allow for the `j`
and `o` flags to be used, without any branching or additional
performance penalty.
New tests and minor refactorings have been included as well.
---
Also included: `bugfix: ensured resty.core can be …

optimize+bugfix: improved heuristics for the PCRE MAP_JIT workaround + support for binaries without PCRE

---

lib/ngx/re.lua
lib/resty/core/regex.lua
t/re-split.t

I considered various alternatives in implementations and testing, but went with a straightforward approach for now.

feature: ngx.re: ensured loading the module without PCRE produces a friendly error.

---

lib/ngx/re.lua

Since we override the `require` function in `resty.base`, the proper
stacktrace level for this error is 3 since it is thrown in the main
chunk of the module.
Example:
Previously, the previous behavior with `resty` was:
$ resty -e 'require "ngx.re"'
ERROR: no support for 'ngx.re' module: OpenResty was compiled without PCRE support
stack traceback:
...
Now, the error contains the chunkame `(command line -e):1:`:
$ resty -e 'require "ngx.re"'
ERROR: (command line -e):1: no support for 'ngx.re' module: OpenResty was compiled without PCRE support
stack traceback:
...
Which is similar to the error reported by other `ngx.re` APIs when
attempting to use them without PCRE support:
$ resty -e 'ngx.re.gmatch()'
ERROR: (command line -e):1: no support for 'ngx.re.gmatch': OpenResty was compiled …

bugfix: ngx.re: fixed the error stacktrace level when missing PCRE support.

---

lib/resty/core.lua
lib/resty/core/shdict.lua

This ensures that all `resty.core` modules setting values under the
`ngx` table can do so without having to enter the `__newindex`
metamethod set by `resty.core.misc`. This commit also includes a style
fix.

optimize: moved 'resty.core.misc' to be loaded last to avoid metatable lookups on 'ngx'.

---

lib/ngx/ssl.lua
lib/ngx/ssl.md
t/ssl.t
t/stream/ssl.t

This PR adds an API that allows users to configure SSL client certificate verification dynamically. For example, Nginx can now read SNI first and then determine whether to request a client certificate during handshake. Optionally, caller can pass in a CA list used for verification.
See https://github.com/openresty/lua-nginx-module/pull/1666 for FFI changes.

feature: implement `ssl.verify_client()`

---

.travis.yml
lib/ngx/balancer.lua
lib/ngx/balancer.md
t/balancer.t

Feature was originally developed by @locao inside https://github.com/Kong/lua-kong-nginx-module/pull/13. With slight modifications from @dndx.
Related PR: https://github.com/openresty/lua-nginx-module/pull/1734.

feature: add the `balancer.recreate_request` function, which allows user to recreate request buffer in balancer phase.

---

lib/resty/core.lua
lib/resty/core/request.lua
lib/resty/core/utils.lua
t/stream/request.t

The `ngx.req.start_time()` API is part of `request.lua` which is was
understandably not loaded for the stream subsystem. There existed no
tests for this API in the stream subsystem, so the removal of its
underlying CFunction resulted in `ngx.req.start_time` being `nil` with
no test cases to realize that.

bugfix: added the missing 'ngx.req.start_time' to the stream subsystem.

---

t/pipe.t

In check_leak mode (`TEST_NGINX_CHECK_LEAK_COUNT=1000`), I run the test case (`t/pipe.t`)
100 times in a loop. 
before the changes were made, `k > 0.0` occurred 60 times, and the max
value of `k` is `2.7`:
``` log
LeakTest: [5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5748 5776 5900 5900 5900 5900 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 5928 …
```

tests: run collectgarbage() before ngx_pipe.spawn() to fix mem leaks in check_leak mode.

---

t/pipe.t

tests: t/pipe.t: --- shutdown_error_log should be excluded from repeat_each() when counting plans.

---

t/ssl-session-fetch.t

tests: t/ssl-session-fetch.t: use TEST_NGINX_RAND_PORT_XXX instead of TEST_NGINX_SERVER_SSL_PORT.

---

t/pipe-stderr.t
t/pipe.t

tests: pipe.t: increase timeout to 1 second to make it more resilient in mockeagain(W) & valgrind mode.

---

lib/resty/core/utils.lua

from https://luajit.org/ext_ffi_api.html
ffi.copy(dst, str)
In this syntax, the source of the copy must be a Lua string. All bytes of the string plus a zero-terminator are copied to dst (i.e. #src+1 bytes).

bugfix: invalid write of size 8 caught by valgrind.

---

t/ocsp.t

tests: ocsp.t: specify the maxlen of the buf_size explicitly to avoid test failure.

---

README.markdown
lib/resty/core/base.lua

 change: allowing both ngx_lua 0.10.18 and 0.10.19.

---

lib/resty/core/base.lua

bumped API version to 0.1.21.

---

lib/ngx/errlog.md

doc: fix typo in the example configuration

---

lib/ngx/balancer.md

Fixed typo in balancer doc

---

README.markdown
lib/resty/core/ctx.lua
t/ctx.t

feature: expose the get_ctx_table API to get the ctx table & support using ctx table from caller when the ctx table is not existing.

---

t/ssl.t

When I run this test case locally, it failed to get the reponse with the following outputs.  
```
^_^$ sh go.sh t/ssl.t
t/ssl.t .. 13/326
t/ssl.t .. 20/326
t/ssl.t .. Failed 6/326 subtests
Test Summary Report
-------------------
t/ssl.t (Wstat: 0 Tests: 328 Failed: 8)
Failed tests:  13-15, 20-22, 327-328
Parse errors: Bad plan.  You planned 326 tests but ran 328.
Files=1, Tests=328, 12 wallclock secs ( 0.09 usr  0.01 sys +  1.05 cusr  0.37 csys =  1.52 CPU)
Result: FAIL
```
It seems the test client timed out beforing receiving response, because `ngx.log(ngx.INFO, out)` has printed log successly. Noticing the max timeout of test server is about 3s, the timeout of client should …

tests: t/ssl.t fix test failure

---

lib/resty/core/ctx.lua

Now `ngx.ctx` is 80% faster than the old implementation.
Here is the Lua bench script:
```
local function table_fetch()
local ctx = ngx.ctx
local t = ctx.t
if not t then
t = 1
ctx.t = t
end
return t
end
local ctx = {}
for i = 1, 1000 * 1000 * 1000 do
table_fetch()
end
print("done")
```
Here is the bench result:
```
$ time resty ctx.lua
done
real    0m8.575s
user    0m8.461s
sys     0m0.055s
$ time resty ctx.lua
real    0m4.672s
user    0m4.578s
sys     0m0.069s
```

optimization: a new upvalue table for the ctxs holder to make LuaJIT JIT compiler happy to generate more efficient machine code.

---

lib/resty/core/regex.lua
t/re-bugs.t

In order to avoid an infinite loop when the regex matches an empty
sub string, we set the match offset(`pos`) one character ahead of
cap\[1\](`cp_pos`) and begin a new match process(in ngx.re.gsub). Then
we break out the loop and make a comparison with #subj to check
whether there is a trailer to concat, in which we should not use
the match offset but the last cap[1].

bugfix: ngx.re.sub/gsub incorrectly dropped the last character.

---

t/balancer.t

tests: t/balancer.t: use RegExp instead of strict character match.

---

lib/resty/core/misc.lua

bugfix: ngx.req.is_internal is only supported in http subsystem.

---

README.markdown

doc: add missing doc for ssl.clienthello

---

lib/resty/core/base.lua

minor fix: get ngx_lua_version before 'not ngx.config'

---

lib/resty/core/base.lua

TRACE --- (1/0) base.lua:192 -- NYI: return to lower frame at ffi.new

optimize: avoid NYI in the get_string_buf function.

---

lib/resty/core/worker.lua

bugfix: windows also need to support ngx_lua_ffi_worker_pids.

---

lib/resty/core/request.lua
t/request.t

Fix a bug that request header contains "_" unable to be case-insensitive matched.
e.g. 
```lua
-- Request with headers:
-- X_Foo_Header: foo
local value = ngx.req.get_headers()["X_Foo_Header"]  -- nil
```

bugfix: request headers contains "_" should be case-insensitive matched.

---

lib/resty/core/time.lua

If https://github.com/openresty/lua-resty-lrucache/pull/55 is correct,
we should do the same thing in resty.core.

optimize: remove NYI call in core.time

---

lib/resty/core/base.lua
t/count.t

Expose `NGX_ABORT` through `FFI_ABORT` - see https://github.com/nginx/nginx/blob/master/src/core/ngx_core.h#L44

feature: expose NGX_ABORT using FFI_ABORT

---

lib/resty/core/time.md

It should be millisecond, not microsecond.

doc: fix the decription of monotonic_msec()

---

lib/resty/core/worker.lua

- call `ngx_lua_ffi_worker_count()` directly
- cache the result of `ngx.get_phase()`

optimize: small optimization of `ngx.worker.pids()`

---

t/pipe.t

tests: t/pipe.t: increase the timeout to 10s for TEST 27.

---

Makefile

echo in sh(/usr/bin/sh -> dash) in ubuntu does not accept the -e option of echo, so we explicit requirement to use bash

optimize: Explicit requirement to use bash

---

lib/ngx/balancer.lua
lib/ngx/balancer.md
t/balancer.t

feature: add balancer.set_upstream_tls(on).

---

lib/ngx/ocsp.lua

For the ocsp response without nextUpdate value, it will get the previous nextUpdate value which is cached in the module-level lua ffi variable, this is not what we expected.
Maybe we should use function-level local variable instead?

bugfix: might get previous nextupdate value

---

valgrind.suppress

Currently each upstream block leaks once. Temporarily ignore these leaks. TODO: Consider adding deallocation logic in nginx core later.

tests: valgrind.suppress: added SSL-related valgrind.suppress entries.

---

t/TestCore.pm
t/TestCore/Stream.pm
t/balancer-keepalive-localaddr.t
t/balancer-keepalive.t
t/stream/balancer-bind.t

Replace fixed ports with randomly assigned ports for `TEST_NGINX_SERVER_SSL_PORT*` variables. This prevents port conflicts when running tests in multiple processes.

tests: Change TEST_NGINX_SERVER_SSL_PORT* to use random ports.

---

lib/resty/core/base.lua

bumped lua-resty-core to 0.1.29.

---

lib/ngx/resp.lua
lib/ngx/resp.md
lib/resty/core/response.lua

I hereby granted the copyright of the changes in this pull request to the authors of this lua-resty-core project.

feature: add bypass_if_checks method to ngx.resp

---

lib/resty/core/socket.lua

bugfix: fix issue #499，to avoid unexpect assertion when c func return FFI_OK immediately.

bugfix: fix sslhandshake  unexpect assertion

---

lib/ngx/ssl/clienthello.lua
lib/ngx/ssl/clienthello.md
t/ssl-client-hello.t

https://github.com/openresty/lua-nginx-module/pull/2419

feature: get_client_hello_ciphers()

---

lib/resty/core/coroutine.lua

optimize: remove unuse param
