openresty/lua-resty-core

- lib/ngx/balancer.lua
> Add missing locals to ngx/balancer.lua

- .travis.yml
- lib/ngx/balancer.lua
- lib/ngx/balancer.md
- t/balancer-timeout.t
> feature: ngx.balancer: added new API functions set_timeouts() for setting upstream timeouts

- .travis.yml
- lib/ngx/ssl.lua
- t/stream/ssl.t
> feature: ssl_certby_lua* support for stream_lua.

- lib/ngx/errlog.lua
- t/stream/errlog-raw-log.t
- t/stream/errlog.t
* Sister PR 1: https://github.com/openresty/meta-lua-nginx-module/pull/48
* Sister PR 2: https://github.com/openresty/stream-lua-nginx-module/pull/121
> feature: errlog: enabled the FFI-based API for the stream subsystem

- README.markdown
> doc: updated the copyright year to 2019.

- t/shared.t
> tests: shared: split shm:ttl() positive and negative test cases.

- .travis.yml
- t/pipe.t
> tests: pipe.t: checked proc:wait() return value when timed out.

- .travis.yml
Thanks Thibault for the report.
> travis-ci: avoided using the contributor's branch of lua-nginx-module.

- README.markdown
> doc: readme: updated the synopsis section for OpenResty 1.15.8.1.

- lib/resty/core/request.lua
- t/request.t
> chore: we already supported set request header with table

- README.markdown
> doc: removed outdated note

- lib/resty/core/phase.lua
> feature: add exit_worker as new phase

- .travis.yml
- t/pipe-stdout.t
- t/request.t
> travis-ci: bumped the NGINX core to 1.19.2.

- t/pipe-stdin.t
> tests: pipe.t: increase proc:write() timeout to 300ms for stability.

- .travis.yml
- t/pipe-multi-workers.t
> test: ensure we don't close listener's fd which was closed.

- lib/resty/core/ctx.lua
- t/ctx.t
> feature: it is harmful to set ngx.ctx to a non-table value

- lib/resty/core/shdict.lua
> bugfix: should compare to nil to check if a cdata is NULL.

- lib/ngx/ssl.md
> doc: update ssl's table of contents

- lib/ngx/process.lua
- t/stream/process-type-hup.t
- t/stream/process-type-master.t
- t/stream/process-type-privileged-agent.t
- t/stream/process-type-single.t
- t/stream/process-type-worker.t
> feature: implemented process API for stream subsystem.

- lib/ngx/process.lua
> style: fixed coding style introduced in commit 044ff52b.

- valgrind.suppress
> tests: added a new rule about 'ngx_pass_open_channel()' to valgrind suppression file.

- .travis.yml
- README.markdown
- lib/resty/core/base.lua
> bumped API version to 0.1.22.

- .travis.yml
- lib/ngx/process.lua
- lib/ngx/process.md
- t/process-type-privileged-agent-connections.t
- t/process-type-privileged-agent.t
add argument connections in process enable_privileged_agent
> feature: add argument connections in process enable_privileged_agent

- t/process-type-privileged-agent.t
trimmed trailing spaces and adjusted alignment.
> style: fixed coding style in t/process-type-privileged-agent.t.

- .travis.yml
- t/process-type-privileged-agent-connections.t
> tests: updated the expected error message in process-type-privileged-agent-connections.t.

- lib/resty/core/misc.lua
> optimize: removed the extra return.

- .travis.yml
> travis-ci: upgrade openssl to 1.1.1m, pcre to 8.45.

- t/balancer-timeout.t
- t/balancer.t
- t/misc.t
- t/process-type-cache.t
- t/process-type-hup.t
- t/process-type-master.t
- t/process-type-privileged-agent.t
- t/process-type-single.t
- t/process-type-worker.t
- t/semaphore.t
- t/ssl-session-fetch.t
- t/ssl-session-store.t
- t/status.t
> tests: update test cases to reflect the latest change of ngx_lua.

- .travis.yml
- lib/resty/core.lua
- lib/resty/core/coroutine.lua
- lib/resty/core/phase.lua
> optimize: reimplemented the coroutine wrapper with ffi api.

- lib/ngx/ssl/clienthello.lua
> optimize: localize bit.bor for ssl.clienthello

- lib/ngx/ssl/clienthello.lua
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> change: standardize the error msg & fix stack level

- .travis.yml
- README.markdown
- lib/resty/core.lua
- lib/resty/core/param.lua
- t/param.t
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> feature: add FFI implementation for ngx.arg getter

- lib/resty/core/request.lua
- t/request.t
> feature: provide a way to reuse table in ngx.req.get_uri_args

- lib/resty/core/phase.lua
> feature: added support for ssl_server_rewrite_by_lua.

- lib/resty/core/response.lua
- lib/resty/core/shdict.lua
This is the workaround for luajit FFI working on apple silicon.
See:
https://github.com/openresty/lua-nginx-module/issues/2030
https://github.com/LuaJIT/LuaJIT/issues/205
Sister PR:
https://github.com/openresty/lua-nginx-module/pull/2037
https://github.com/openresty/stream-lua-nginx-module/pull/293
> bugfix: Apple silicon workaround

- lib/resty/core/base.lua
> optimization: localize pcall in base.lua

- .travis.yml
- lib/ngx/pipe.lua
- t/pipe.t
>  optimize: destroy pipe when freeing request.

- lib/resty/core/base.lua
> Merge v0.1.24 into master.

- .travis.yml
- README.markdown
- lib/resty/core/time.lua
- lib/resty/core/time.md
- t/stream/time.t
- t/time.t
> feature: add new api  "resty.core.time".monotonic_time.

- lib/resty/core/base.lua
> new: bumped version to 0.1.25.

- t/require.t
> tests: updated the pattern of the expected output of t/require.t.

- t/pipe-stdout.t
> tests: update the test to refect the latest change in lua-nginx-module.

- .travis.yml
> tests: CI failed due to conflict of prove from difference source.

- lib/resty/core/base.lua
> pkg: bumped version to 0.1.26.

- lib/resty/core/worker.lua
Summary
- var `is_not_windows`
- table size is `5` on unix like system
- minor style fix
> style: some style fix for worker.pids

- .travis.yml
- t/ctx.t
- t/ssl-session-fetch.t
> tests: fixed test failure.

- lib/resty/core/base.lua
> bumped version to 0.1.27.

- lib/resty/core/request.lua
> feature: allow get empty key for ngx.req.get_uri().

- .travis.yml
- t/ctx.t
- t/ssl-session-fetch.t
- t/ssl-session-store.t
- util/ver-ge
https://github.com/openresty/openresty/pull/920
> new: upgrade nginx core to 1.25.1

- README.markdown
> doc: update dependencies' version

- lib/ngx/balancer.md
- lib/ngx/errlog.md
- lib/ngx/ocsp.md
- lib/ngx/pipe.md
- lib/ngx/process.md
- lib/ngx/re.md
- lib/ngx/req.md
- lib/ngx/resp.md
- lib/ngx/ssl/clienthello.md
> doc: change some APIs from experimental to production ready.

- lib/resty/core/base.lua
> bumped version to 0.1.28.

- lib/ngx/ssl.lua
- t/ssl.t
- t/stream/ssl.t
> feature: add ssl.get_client_random.

- lib/ngx/ssl.md
> doc: add doc for ssl.get_client_random

- lib/ngx/ssl.lua
- lib/ngx/ssl.md
- t/ssl.t
Requires https://github.com/openresty/lua-nginx-module/pull/1286
> feature: Add ssl.get_ssl_pointer

- lib/resty/core.lua
- lib/resty/core/socket.lua
> feature: add support for sock:send_cdata(cdata, len).

- lib/resty/core/worker.lua
> optimize: localize tonumber for ngx.worker.pids

- lib/ngx/ssl/clienthello.md
> doc: add ToC entry for 'get_supported_versions'

- .travis.yml
- lib/ngx/balancer.lua
- lib/ngx/balancer.md
- t/TestCore.pm
- t/balancer-keepalive.t
- t/balancer.t
- t/stream/balancer-keepalive.t
- valgrind.suppress
Co-authored-by: Thibault Charbonnier <thibaultcha@me.com>
> feature: implemented keepalive pooling in 'balancer_by_lua*'. (#43)

- .travis.yml
> test: remove build duplicate param

- valgrind.suppress
> tests: fixed malformed valgrind.suppress.

- t/pipe.t
> tests: t/pipe.t: updated plan tests number.
